### PR TITLE
Add Microverse badge to the template

### PR DESCRIPTION
**Pull request by davidauza-engineer**
Added a very nice Microverse badge to the document.

### CODE REVIEW

**Comment by davidauza-engineer** [comment]
@nidalaa I'm not sure if you already did this, but don't forget to set the repository as a template as directed [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) 😊

**Comment by nidalaa** [comment]
Hi @davidauza-engineer !
I will need to consult it with designers first :)

**Comment by davidauza-engineer** [comment]
@nidalaa Sure, thank you very much. Please let me know their opinions  😊

For me, it looks very nice :D 

Screen Shot 2019-12-04 at 9 09 42 AM

**Comment by davidauza-engineer** [comment]
Hi @nidalaa , any new about this change 😊?

**Comment by nidalaa** [comment]
Hi @davidauza-engineer one of the hardest parts of being programmer is obviously naming but the second is making sure that graphics are pixel perfect when it comes to brand recognition.

As we have changed our logo recently, it is still on -hold!
 I am sorry!

**Comment by davidauza-engineer** [comment]
Hi @nidalaa Thank you for your reply, I'll keep waiting for an answer then. Thank you :)

**Comment by davidauza-engineer** [comment]
Hi @nidalaa 

Oh ok. I'll keep waiting for an answer then.

Thank you :)

**Comment by nidalaa** [comment]
Late answer but at least a positive one! Let's merge it! 💥 

Thank you @davidauza-engineer !

**Pull request merged**
